# theme: plainwhite
title:       "K.A"
# author:      K.A
url:         "http://kasabaimo.github.io"
# description: "ka website"
show_excerpts: false

baseurl: '/kablog'

plainwhite:
  name: K.A
  tagline: Sales Trader and Data Scientist at Société Générale
  date_format: "%b %-d, %Y"
  sitemap: true 
  search: false 
  dark_mode: true
  portfolio_image: "assets/images/logo.jpg" 
  html_lang: "en" 
  condensed_mobile:
    #- home
    - page
    - post
  # generate social links in footer
  social_links:
    # twitter: nannevn
    github:  kasabaimo
    linkedIn: in/kentaro-asaba
    # scholar: wFDJzDkAAAAJ
  navigation: 
    - title: Home
      url: "/kablog/"
    - title: About
      url: "/kablog/about"
    # - title: Contact
    #   url: "mailto:n.j.e.vannoord@uva.nl"

# Build settings
markdown:     kramdown
permalink:    pretty
sass:
        sass_dir: _sass
