title: K.Asaba
description: A minimal and beautiful Jekyll theme best for writing and note-taking.
author: K.Asaba
avatar: assets/images/logo.jpg
# email: ngzhio@gmail.com

# url is currently only used only for the RSS feed in feed.xml
baseurl: '/kablog'
url: 'https://kasabaimo.github.io/'

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

htmlwidgets: TRUE

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Jekyll SEO Tag (Optional)
# =========================
# twitter:
#   username: ngzhio
#   card: summary
logo: logo.png
# social:
#   name: Shangzhi Huang
#   links:
#     - https://twitter.com/ngzhio
#     - https://www.facebook.com/ngzhio
#     - https://github.com/ngzhio
# google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
